version: '3'
services:
  buggy-scripts:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "buggy-scripts"
    ports:
    - 5000:5000
    volumes:
      - ./conf.json:/app/conf/conf.json
      - ./runners/:/app/conf/runners
      - ./scripts/:/app/scripts/
      - /var/run/docker.sock:/var/run/docker.sock
